# Generated by Django 5.2.15 on 2026-06-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectmember_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(default='member', max_length=20),
        ),
    ]
